### PR TITLE
WAD and KMF

### PR DESCRIPTION
**Pull request by ArchDemons**
added wad compressed format but memory leak
fixed kmf file structure (suppor anim and grop now)
small fixes last revision

### CODE REVIEW

**Comment by ufdada** [comment]
Well the memory leak is really unfortunate, but i think it should be ok for now.

**Comment by ufdada** [comment]
It looks like the memory leak wasn't introduced with the decompression, it just got more noticeable.

**Comment by ArchDemons** [comment]
maybe. I tried to find any function to clear memory, but did not find. Another reason - to many items in WAD file (2500 in Meshes). We can modify script to extract part of items if items more than ...

**Comment by ufdada** [comment]
By fiddling around with the script it seems the editor is generally not good in garbage collecting and has some leaks on its very own. Especially the copying of byte-array values (from src to dest) uses alot of memory with can't be freed (it even crashed my computer...).

I also think it's better to just partly extract contents of the Meshes.wad, if we need to, before wasting our time.

**Pull request merged**
